url: https://gce-korea.github.io
baseurl: /

# Site settings
title: GitHub Campus Experts Korea
email: githubcampusexperts.korea@gmail.com
description: "Hello! We are GitHub Campus Experts from Korea."


# Team names, titles and social links
people:
- name: YouJin Jung
  pic: 1
  position: "GitHub Campus Expert \n @ Ewha Womans University"
  social:
    - title: map-pin
      url: https://githubcampus.expert/jung-youjin
    - title: github
      url: https://github.com/jung-youjin
    - title: linkedin
      url: https://bit.ly/jung-youjin
    - title: envelope
      url: mailto:jungyoujin0527@gmail.com
    - title: globe
      url: https://youjinjung.me

- name: Mukhtar Kussaiynbekov
  pic: 2
  position: "GitHub Campus Expert \n @ KAIST"
  social:
    - title: map-pin
      url: https://githubcampus.expert/mukhtarkussaiynbekov
    - title: github
      url: https://github.com/mukhtarkussaiynbekov
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: users
    url: https://githubcampus.expert
  - title: globe
    url: https://gce-korea.github.io
  - title: envelope
    url: mailto:githubcampusexperts.korea@gmail.com
  - title: github
    url: https://github.com/gce-korea

# Postal address (add as many lines as necessary)
address:
  - line: South Korea

# Build settings
markdown: kramdown
permalink: pretty
